-- +migrate Up
DROP TABLE IF EXISTS `cine_vod`;
CREATE TABLE `cine_vod` (
    `vod_id` int NOT NULL AUTO_INCREMENT COMMENT '编号',
    `type_id` bigint DEFAULT NULL COMMENT '类型编号',
    `type_id_1` bigint DEFAULT NULL COMMENT '子类型编号',
    `group_id` bigint DEFAULT NULL COMMENT '分组编号',
    `vod_name` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '剧名',
    `vod_sub` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '副标题',
    `vod_en` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '英文名',
    `vod_status` tinyint(1) DEFAULT NULL COMMENT '状态',
    `vod_letter` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '首字母',
    `vod_color` varchar(6) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '颜色',
    `vod_tag` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '标签',
    `vod_class` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '分类',
    `vod_pic` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '封面',
    `vod_pic_thumb` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '缩略图',
    `vod_pic_slide` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '海报',
    `vod_pic_screenshot` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '截图',
    `vod_actor` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '演员',
    `vod_director` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '导演',
    `vod_writer` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '编剧',
    `vod_behind` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '幕后人员',
    `vod_blurb` text COLLATE utf8mb4_general_ci COMMENT '剧情简介',
    `vod_remarks` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
    `vod_pubdate` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '发行日期',
    `vod_total` bigint DEFAULT '1' COMMENT '总集数',
    `vod_serial` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '连载状态',
    `vod_tv` varchar(30) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '电视台',
    `vod_weekday` varchar(30) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新日',
    `vod_area` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '地区',
    `vod_lang` varchar(10) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '语言',
    `vod_year` varchar(10) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '年份',
    `vod_version` varchar(30) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '版本',
    `vod_state` varchar(30) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '状态',
    `vod_author` varchar(60) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '作者',
    `vod_jumpurl` varchar(150) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '跳转',
    `vod_tpl` varchar(30) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '模板',
    `vod_tpl_play` varchar(30) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '播放模板',
    `vod_tpl_down` varchar(30) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '下载模板',
    `vod_isend` tinyint(1) DEFAULT NULL COMMENT '是否完结',
    `vod_lock` tinyint(1) DEFAULT NULL COMMENT '是否锁定',
    `vod_level` tinyint(1) DEFAULT NULL COMMENT '等级',
    `vod_copyright` tinyint(1) DEFAULT NULL COMMENT '版权',
    `vod_points` bigint DEFAULT '0' COMMENT '积分',
    `vod_points_play` bigint DEFAULT '0' COMMENT '播放积分',
    `vod_points_down` bigint DEFAULT '0' COMMENT '下载积分',
    `vod_hits` bigint DEFAULT '0' COMMENT '总点击量',
    `vod_hits_day` bigint DEFAULT '0' COMMENT '日点击量',
    `vod_hits_week` bigint DEFAULT '0' COMMENT '周点击量',
    `vod_hits_month` bigint DEFAULT '0' COMMENT '月点击量',
    `vod_duration` varchar(10) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '单集时长',
    `vod_up` bigint DEFAULT '0' COMMENT '顶数',
    `vod_down` bigint DEFAULT '0' COMMENT '踩数',
    `vod_score` float DEFAULT NULL COMMENT '当前评分',
    `vod_score_all` bigint DEFAULT '0' COMMENT '总评分',
    `vod_score_num` bigint DEFAULT '0' COMMENT '评分人数',
    `vod_time` int DEFAULT '0' COMMENT '更新时间',
    `vod_time_add` int DEFAULT '0' COMMENT '添加时间',
    `vod_time_hits` int DEFAULT '0' COMMENT '点击时间',
    `vod_time_make` int DEFAULT '0' COMMENT '制作时间',
    `vod_trysee` bigint DEFAULT '0' COMMENT '试看集数',
    `vod_douban_id` int DEFAULT '0' COMMENT '豆瓣ID',
    `vod_douban_score` float DEFAULT NULL COMMENT '豆瓣评分',
    `vod_reurl` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '重定向URL',
    `vod_rel_vod` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '相关影视',
    `vod_rel_art` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '相关文章',
    `vod_pwd` varchar(10) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '密码',
    `vod_pwd_url` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '密码页URL',
    `vod_pwd_play` varchar(10) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '播放密码',
    `vod_pwd_play_url` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '播放页URL',
    `vod_pwd_down` varchar(10) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '下载密码',
    `vod_pwd_down_url` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '下载密码URL',
    `vod_content` text COLLATE utf8mb4_general_ci COMMENT '剧情介绍',
    `vod_play_from` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '播放来源',
    `vod_play_server` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '播放服务器',
    `vod_play_note` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '播放说明',
    `vod_play_url` text COLLATE utf8mb4_general_ci COMMENT '播放地址',
    `vod_down_from` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '下载来源',
    `vod_down_server` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '下载服务器',
    `vod_down_note` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '下载说明',
    `vod_down_url` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '下载地址',
    `vod_plot` tinyint(1) DEFAULT NULL COMMENT '是否有分集剧情',
    `vod_plot_name` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '分集剧情名称',
    `vod_plot_detail` text COLLATE utf8mb4_general_ci COMMENT '分集剧情详情',
    PRIMARY KEY (`vod_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- +migrate Down
DROP TABLE IF EXISTS `cine_vod`;